

use mysql;
SELECT * FROM user;
drop user 'ggoomter'@'localhost';
create user 'ggoomter'@'localhost' identified by '0070';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO `ggoomter`@`localhost` WITH GRANT OPTION;
SHOW GRANTS FOR 'ggoomter'@'localhost';	-- 해당유저의 권한조회
FLUSH PRIVILEGES;
